name: Spring Boot CI/CD

on:
    push:
        branches:  ["main" , "mockito"]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Build & Test
              run: mvn clean verify

            - name: Generate Surefire Report
              run: mvn surefire-report:report

            - name: Generate JaCoCo Report
              run: mvn jacoco:report
              

            - name: Upload Test Report
              uses: actions/upload-artifact@v4
              with:
                name: test-reports
                path: |
                  target/site
                  target/site/jacoco
                  
    deploy-staging:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop' && needs.build.result == 'success'
        steps:
            - name: Trigger Render Staging Deploy
              run: curl -X POST ${{ secrets.RENDER_STAGING_HOOK }}

    deploy-prod:
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
      steps:
        - name: Trigger Render Prod Deploy
          run: curl -X POST ${{ secrets.RENDER_PROD_HOOK }}
